feat: migrate create command to standalone package
umijs/tnf pull request #27
Opened 2024-11-12 10:00 UTC by QDyanbing

主要更改：
功能迁移：将 create 命令逻辑从主包中提取到 create-tnf 独立包。
路径调整：在主包中修改了导入路径，使其指向构建后文件的正确位置。

2024-11-12 12:57 UTC, sorrycc requested changes

2024-11-12 12:57 UTC, sorrycc commented on package.json
> +    "create-tnf": "^0.1.2",
抱歉，可能前面没说清楚。

1、create-tnf 单独成包，不作为主包的依赖
2、主包里删除 create 命令

2024-11-12 12:57 UTC, sorrycc commented on package.json
> -    "@commitlint/config-conventional": "^19.0.3"
这个不要挪位置。

2024-11-12 12:57 UTC, sorrycc commented on create-tnf/package.json
> +  "types": "dist/types/index.d.ts",
1、应该没有 dist/types/index.d.ts 吧
2、要加个 create-tnf 的 bin
3、templates 目录要挪到 create-tnf 下

2024-11-12 12:57 UTC, sorrycc commented
记得提交前先执行 pnpm ci 。

2024-11-12 13:23 UTC, QDyanbing commented on package.json
> +    "create-tnf": "^0.1.2",
就是整个主包的create 命令提出成为单独的包；主包不再提供create相关的命令了是吧；那了解了；明天重新处理下

2024-11-13 03:45 UTC, xiaohuoni commented on create-tnf/src/index.ts
> +setNoDeprecation();
这些操作看起来没什么必要，感觉可以删掉 fishkit/node 和 constants 文件

2024-11-13 03:50 UTC, xiaohuoni commented on create-tnf/package.json
> +  "name": "@umijs/create-tnf",
包名可以直接用 create-tnf ，更方便使用

2024-11-13 03:50 UTC, xiaohuoni commented on create-tnf/package.json
> +  "name": "@umijs/create-tnf",
https://www.npmjs.com/package/create-tnf

2024-11-13 05:31 UTC, QDyanbing commented on create-tnf/package.json
> +  "name": "@umijs/create-tnf",
👌等 @sorrycc 提交后我再调整下

2024-11-13 05:49 UTC, QDyanbing commented on create-tnf/src/cli.ts
> +import assert from 'assert';
这个没用到

2024-11-13 05:54 UTC, merged