feat:import path for global styles
umijs/tnf pull request #28
Opened 2024-11-12 10:46 UTC by iamwangqing

Add write src/global.{less,css} to client entry. The issue address is [no.26](https://github.com/umijs/tnf/issues/26)

2024-11-12 12:59 UTC, sorrycc approved these changes

2024-11-12 13:00 UTC, sorrycc commented
提交前记得执行下 pnpm ci 。

2024-11-13 01:02 UTC, iamwangqing commented
好的，下次注意

2024-11-13 01:28 UTC, xiaohuoni commented
@iamwangqing changeset 没提交

2024-11-13 01:32 UTC, xiaohuoni commented on src/sync.ts
> +${globalStyleImportPath}
应该在 tailwind 之前，global 最前，权重最低。

2024-11-13 01:37 UTC, iamwangqing commented on src/sync.ts
> +${globalStyleImportPath}
好的，我整改一下，谢谢各位大佬指点

2024-11-13 01:59 UTC, sorrycc requested changes

2024-11-13 01:59 UTC, sorrycc commented on src/sync.ts
> +${overridesStyleImportPath}
overrides 不要，这个如果要加得讨论下，感觉需求不强烈。

2024-11-13 02:05 UTC, xiaohuoni commented on src/sync.ts
> +${overridesStyleImportPath}
overrides 在这里不能达到预期的效果。
然后，在 umi 里面，global.css 的歧义很大，由于页面都是 lazy load 的，所以在 global 写的组件（多为 antd）样式，并不会生效。所以使用到 antd 的时候，overrides 几乎是必须的。

2024-11-13 02:09 UTC, sorrycc commented on .changeset/stupid-tomatoes-work.md
> +Added the ability to write global and overrides style files
```suggestion
Support conventional src/global.{less,css} as global style
```

2024-11-13 02:10 UTC, iamwangqing commented on src/sync.ts
> +${overridesStyleImportPath}
那暂时先不加吗，等讨论确定之后在加？

2024-11-13 02:10 UTC, sorrycc approved these changes

2024-11-13 02:10 UTC, xiaohuoni commented on src/sync.ts
> +${overridesStyleImportPath}
嗯

2024-11-13 02:11 UTC, merged